# Generated by Django 4.1 on 2022-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=32)),
                ("SupplierName", models.CharField(max_length=60)),
                ("phone", models.CharField(max_length=60)),
                ("address", models.CharField(max_length=60)),
                ("email", models.CharField(max_length=60)),
                ("SupplierDepositBank", models.CharField(max_length=60)),
                ("SupplierCorporateAccountNumber", models.CharField(max_length=60)),
                ("NumberOfEmployees", models.CharField(max_length=60)),
                ("AnnualOperatingIncome", models.CharField(max_length=60)),
                ("TotalAssets", models.CharField(max_length=60)),
                ("IsMicroEnterprise", models.BooleanField()),
            ],
        ),
    ]
