# Generated by Django 4.1.1 on 2022-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Second', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='img',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
