# Generated by Django 4.1.1 on 2022-10-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Second', '0003_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Bsqr',
        ),
    ]
